# Generated by Django 4.0.4 on 2022-05-30 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pattes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('ingredients', models.TextField(max_length=600)),
                ('prix', models.FloatField(default=None)),
                ('vegetarienne', models.BooleanField(default=False)),
                ('bio', models.BooleanField(default=False)),
            ],
        ),
    ]
